### PR TITLE
Fixed multiple issues with translation and OneClick

### PR DESCRIPTION
**Pull request by 0x0verflow**
## OneClick
Made UI more user-friendly:
- Smaller window
- Flipped log for more natural reading
- Closing countdown for option "close"
- Fixed missing translation
- Fixed grid

OneClick UI

## Translation
German:
- Fixed Typo
- Added missing translations

Other languages: 
- Added needed translations for futur use

## Other changes
OneClick:
- Added Api to clear title
- Added Api to write line without \n

### CODE REVIEW

**Comment by Assistant** [comment]
This PR is way to big and encompass too many changes, some which would stand on their own but others that won't. I can't accept it in this state.

**Comment by 0x0verflow** [comment]
Okay. I'll open another pull-request for the translations and another one for the OneClick window if you're okay with it. I think you'll at least need the translation. If there is no need for my changes to the OneClick window, then let me know as I won't need to open a third PR for this.

**Comment by Heite92** [comment]
If you create a new pull request, could you please also correct this in de.xaml:

Line 101

`    <sys:String x:Key="Mods:UninstallBox:Body1">Bist du dir sicher das du {0} entfernen möchtest?</sys:String>`

to

`    <sys:String x:Key="Mods:UninstallBox:Body1">Bist du dir sicher, dass du {0} entfernen möchtest?</sys:String>`

**Comment by mhombach** [comment]
@0x0verflow Are you still working on this PR?

**Comment by 0x0verflow** [comment]
Oh, completely forgot about that... I'm sorry! 
I think I'll better close this PR as I don't know, when I'll start working on it again - or even if I ever will. I hope you all don't mind me having it left open, as I said I forgot about it. 
But I'll keep my fork of the repository in case anyone wants to ship my changes in his/her own PR - I would appreciate it.

**Pull request closed without merging**
