### PR TITLE
Added PlaylistManager as a default mod

### PR DESCRIPTION
**Pull request by rithik-b**
Reasoning: [PlaylistManager](https://github.com/rithik-b/PlaylistManager) is a core mod now and a replacement for PlaylistCore

### CODE REVIEW

**Review by lolPants — CHANGES_REQUESTED** [review]
after some internal discussion, we have decided not to set `MorePlaylists` as a default mod. send in another commit to remove it and we'll merge this PR

**Comment by rithik-b** [comment]
It's done!

**Review by lolPants — APPROVED** [review]

**Comment by Meivyn** [comment]
> after some internal discussion, we have decided not to set `MorePlaylists` as a default mod. send in another commit to remove it and we'll merge this PR

Would really like to know your point about this, since ModelDownloader was accepted as a default mod, and do basically the same thing.

**Comment by lolPants** [comment]
> Would really like to know your point about this, since ModelDownloader was accepted as a default mod and do basically the same thing, but with models instead of playlists.

the core team had some internal discussion and many of us don't like the idea of default mods beyond what is "required" to play custom songs (BSIPA and SongCore). the ModelDownloader PR was accepted before we had this discussion, and whether it stays as a default mod is TBD.

personally I am against the idea of default mods altogether but things like this are agreed upon by the core team. considering MA already has the ability to remember what mods you have selected, the concept of "default" mods seems redundant. this leads into another issue where people confuse the default mods behaviour with MA not remembering which mods they had selected. it's confusing that even if you uncheck something like downloader, it'll check it again next time you start MA.

**Comment by n3tman** [comment]
IMO, BeastSaber (BSaber) playlists should be accessible for everyone who uses ModAssistant by default.

Reasoning:
- It's a safe source that plays a big role in helping new and old players find great maps
- It was a part of the core/default mod before (BeatSaverDownloader): https://github.com/andruzzzhka/BeatSaverDownloader/blob/master/BeatSaverDownloader/UI/FlowCoordinators/MorePlaylistsFlowCoordinator.cs#L19

The only potential problem (as I see it now) is that @rithik-b added support for custom playlist sources such as Hitbloq.
It can be considered "unofficial" and maybe even raise some security questions (since remote files can be changed).

However, if @rithik-b leaves only BeastSaber source in this mod, would you consider it essential and tick by default?
I heard there are some plans to make other custom sources in MorePlaylists pluggable. I think it will be the best solution.

**Comment by rithik-b** [comment]
Hitbloq is not an unverified source by any means and is used by most of the community 
Besides, the mod only parses json files, and downloads songs from BeatSaver, there are no security issues due to that.

**Pull request merged**
