### PR TITLE
Check if Playlists folder exists before downloading

### LINKED ISSUE #208: Playlist downloader
I don't know if it is intentional or not, but the playlist downloader doesn't work if the playlist is not in the playlists folder. It also doesn't create a playlists folder if there isn't one already

### PR DESCRIPTION
**Pull request by Parapass**
should close #208
it makes the folder if it cant find it
make any changes, if it doesnt compile at all ill just close it since im bad

### CODE REVIEW

**Comment by megalon** [comment]
Close!
You just needed to put it in a function call and combine the base path and the playlist path.
I've put it into a static function and called that on application startup.

Does this address both issues in that report?
I'm not sure about this part
`the playlist downloader doesn't work if the playlist is not in the playlists folder`

**Comment by mhombach** [comment]
@Parapass Are you still working on this PR? If not, please close it, so that someone else can work on the issue.

**Comment by Parapass** [comment]
> `the playlist downloader doesn't work if the playlist is not in the playlists folder`

shouldn't this kill 2 birds with one stone, as it makes the playlist folder if it cant find it in the main bs directory?

**Comment by lolPants** [comment]
I've made a few cleanups, going to merge, If the issue with downloading not working for external playlists is still present it can be addressed in a separate PR.

**Pull request merged**
