### PR TITLE
Fix infinite 'checking installed mods'

### LINKED ISSUE #464: Stuck on Loading Mods
When I started ModAssistant today to check for mod updates, and clicked on the Mods button, it didn't do anything. It is currently stuck, it appears, on Checking Installed Mods. The screen just has the Loading Mods symbol continually rotating and it's otherwise not doing a thing.

I can get to the other screens and interact with them.

I've uninstalled and reinstalled Beat Saber and ModAssistant, restarted the computer between each uninstall and reinstall, started up Beat Saber, deleted everything related to ModAssistant and Beat Saber, restarted again (not all in that exact order), and it's still not working.

I've attached the error messages I got when trying to uninstall mods and BSIPA before I uninstalled Beat Saber. After getting those errors, ModAssistant shut down.

Any ideas?

error1
error2

### PR DESCRIPTION
**Pull request by Parapass**
Closes #464

### CODE REVIEW

**Comment by Parapass** [comment]
its what fixed it for me, might work, might not work

**Comment by Siscily** [comment]
Can't say I know what to do with that. Is it a file I need to download and put somewhere? Or something I need to edit in a file somewhere? I've got no clue.

**Comment by Tazzetiel** [comment]
> Can't say I know what to do with that. Is it a file I need to download and put somewhere? Or something I need to edit in a file somewhere? I've got no clue.

We users gotta wait for this fix to be fully implemented and released is my guess.

**Comment by Parapass** [comment]
Here's a test build. See if it works on your end.

https://drive.google.com/file/d/1n8HZwiBPT93IM_3SbDDJkZXtEdBubkTw/view?usp=sharing

**Comment by Tazzetiel** [comment]
> Here's a test build. See if it works on your end.
> 
> https://drive.google.com/file/d/1n8HZwiBPT93IM_3SbDDJkZXtEdBubkTw/view?usp=sharing

so far had it load a bit over 2 minutes and not loading successfully. depeted the old exe file aswell to make sure it doesnt somehow interfere...

**Comment by TheNeverK** [comment]
Well, you've nerd-sniped me and I begun some debugging. Your fix works, but it doesn't solve the root of the problem. It seems like [JsonSerializer.Deserialize](https://github.com/Assistant/ModAssistant/blob/e343a0f3d2f55b6a66ef2f6dbff4331c193a69ec/ModAssistant/Pages/Mods.xaml.cs#L167) silently throws an InvalidOperationException, and the CheckInstalledMods never moves on. I haven't found the culprit yet but if anyone's interested here's the stack trace:
```
Exception thrown: 'System.InvalidOperationException' in System.Web.Extensions.dll
System.InvalidOperationException: Cannot convert object of type 'System.String' to type 'ModAssistant.Mod+Dependency[]'
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeMain(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.AssignToPropertyOrField(Object propertyValue, Object o, String memberName, JavaScriptSerializer serializer, Boolean throwOnError)
   at System.Web.Script.Serialization.ObjectConverter.ConvertDictionaryToObject(IDictionary`2 dictionary, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeMain(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.AddItemToList(IList oldList, IList newList, Type elementType, JavaScriptSerializer serializer, Boolean throwOnError)
   at System.Web.Script.Serialization.ObjectConverter.ConvertListToObject(IList list, Type type, JavaScriptSerializer serializer, Boolean throwOnError, IList& convertedList)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeMain(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
   at ModAssistant.Pages.Mods.<GetAllMods>d__19.MoveNext() in D:\projects\ModAssistant\ModAssistant\Pages\Mods.xaml.cs:line 172
```

**Comment by TheNeverK** [comment]
Yup, it works now. Thanks

**Pull request closed without merging**
