### PR TITLE
Add ScrollViewer for non Mod pages

### PR DESCRIPTION
**Pull request by megalon**
Wraps the Grid objects with a ScrollViewer.
The scrollbar will only appear when needed.

All other changes are just auto formatting.

https://user-images.githubusercontent.com/27714637/118077823-c1d79080-b369-11eb-8759-63040847a571.mp4

### CODE REVIEW

**Review by lolPants — COMMENTED** [review]
Is this strictly necessary? I always thought Mod Assistant had a minimum window size which was set to the default size; perhaps it would be easier to implement that.

At the very least we should define **some** minimum size, regardless of whether it's the current default size or not.

**Comment by megalon** [comment]
We could set a minimum size for MA, but I personally like being able to resize windows to however small I need them to be on screen.

I was actually experimenting with scrollbars because the Options page is so crowded, adding one or two new lines quickly overflows off the page, and adding these scrollbars was surprisingly simple. Being able to scroll the pages when resizing is just an easier way to demonstrate the scrollbars.

Also, the different translations can change the width of the text boxes, and we would have to determine a min window size based on whichever language has the max width. (Currently the Russian translation, I believe). This wouldn't be a concern if we had scrollbars.

image


As far as simplicity goes, it looks like a lot has change in the files, but I just wrapped each of the main Grid objects with `<ScrollViewer HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto">` and a closing `</ScrollViewer>`. The additional changes are just auto formatting to increase indentation of the child elements.

**Comment by lolPants** [comment]
> I personally like being able to resize windows to however small I need them to be on screen.

As much as I agree with this, there has to be a limit. Beyond a certain point the UI is just unusable.
image

**Comment by megalon** [comment]
Yeah you're right

I think `800 px` x `430 px` would be a good minimum size.
In the English translation, it only adds the horizontal scrollbar for the About page.

Screenshots:

image

image

image

image

**Comment by lolPants** [comment]
👍

**Comment by megalon** [comment]
Ok, I think this is ready to merge if it looks good to you!

**Review by lolPants — APPROVED** [review]

**Pull request merged**
